# Generated by Django 3.2.25 on 2024-04-17 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240417_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
