INSERT INTO api_category (name, description, img) VALUES ('Public', 'Public buses are a form of public transportation designed to transport passengers within a city or region. They play a crucial role in urban infrastructure, providing accessibility and convenience for many individuals.', );
INSERT INTO api_category (name, description, img) VALUES ('Intercity', 'Intercity buses, also known as coach or long-distance buses, are a mode of transportation designed to travel between cities and towns over longer distances.Overall, intercity buses play a vital role in connecting communities, facilitating travel between cities and towns, and providing accessible and affordable transportation options for passengers traveling longer distances.');
INSERT INTO api_category (name, description, img) VALUES ('Tour', 'Tour buses are specialized vehicles designed for leisure travel, sightseeing, and guided tours.Overall, tour buses offer a convenient, comfortable, and immersive way to experience travel and exploration. Whether embarking on a guided sightseeing tour or a customized adventure, tour buses provide passengers with memorable experiences and opportunities for discovery.');
INSERT INTO api_category (name, description, img) VALUES ('Night', 'Night buses, also known as overnight buses or sleeper buses, are a type of transportation service that operates during nighttime hours, typically covering long distances between cities or destinations. Overall, night buses offer a practical and economical means of long-distance travel, allowing passengers to rest comfortably while journeying to their destination overnight. They provide a convenient and efficient transportation option for travelers seeking to maximize their time and budget during their travels.');
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Mercedes Tourismo', 'Is a renowned coach manufactured by the German automobile manufacturer. Overall, the Mercedes-Benz Tourismo is a premium coach that offers a combination of luxury, performance, and safety.', 1000, 1);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Volvo 9700', 'Is a popular coach manufactured by the Swedish automotive company Volvo. The Volvo 9700 is a well-designed, reliable, and versatile coach that offers passengers a comfortable and safe travel experience.', 1200, 2);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Scania Interlink', ' Is a versatile and efficient bus model manufactured by the Swedish automotive company Scania. The bus may be equipped with modern infotainment systems, Wi-Fi connectivity, and onboard entertainment options', 800, 3);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Neoplan Starliner', ' is a premium coach manufactured by the German company Neoplan, a subsidiary of MAN Truck & Bus AG. These features may include electronic stability control, anti-lock brakes, adaptive cruise control, lane-keeping assist, ', 1500, 4);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Setra S 431 DT', 'Is a luxurious double-decker coach manufactured by Setra, a subsidiary of the German automotive company Daimler AG. It is available in different configurations, with options for seating capacity, interior layouts, and amenities.', 1100, 1);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('MAN Lions Coach', 'Is designed to provide passengers with a comfortable and spacious travel experience. It features ergonomic seating with ample legroom, large windows for panoramic views, and adjustable amenities', 1300, 2);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Van Hool TDX27 Astromega', 'Is renowned for its spacious and comfortable interior design. It features multiple seating configurations, including standard seating, executive seating, and sleeper berths, to accommodate various passenger', 1600, 3);
INSERT INTO api_bus (name, description, price, category_id) VALUES ('Irizar i8', 'Is characterized by its sleek and modern exterior design. It features clean lines, aerodynamic contours, and stylish accents that give it a distinctive and sophisticated appearance on the road.', 1800, 4);

DELETE FROM api_bus where id = 38;
